### ISSUE TITLE
Text generation stopped working

### ISSUE THREAD

**Issue by spaceoutlaws** [SalokinGreen/NAI4Obsidian#5]
Hi there! After NovelAI's servers came back up after maintenance today, text generation in Obsidian doesn't seem to be working. I've restarted everything and even generated a new API key to troubleshoot, but nothing's worked. Do you have any ideas?

**Comment by spaceoutlaws** [comment]
Hello again! Did some digging and I believe the issue is being caused by NovelAI swapping to a new domain for their text generation API: https://text.novelai.net/docs/index.html

I'm not sure how to access /utils/generator.ts locally (I don't really know what I'm doing) to change the URL myself, unfortunately.

**Comment by SalokinGreen** [comment]
Hey there, apologies for the inconvenience. To be honest, I had quite some time to fix that issue, NovelAI announced the api change at the start of September, but really unfortunately I got covid around that time too and I'm still recovering. I will try my best to push out a fix for Kayra tomorrow and work on adding Erato the next days. 🙏

**Comment by spaceoutlaws** [comment]
@SalokinGreen No need to apologize! I hope you feel better soon, and thank you so much for the updates. :) I'm honestly just relieved you replied — I love this plugin so much.

**Comment by SalokinGreen** [comment]
@spaceoutlaws I updated the plugin to work with the new api. Should work now again! I will add the new generation settings soon and Erato soon-ish. Erato requires a little bit more tinkering than normal.

**Comment by spaceoutlaws** [comment]
@SalokinGreen AMAZING!! Thank you so much :’)

**Comment by spaceoutlaws** [comment]
@SalokinGreen I'm so sorry to bother again, but I'm still not able to get text generation to work. :( I can't tell if it's on my end or not.

EDIT: Oh, wait, it looks like Clio is working, but not Kayra.

**Comment by SalokinGreen** [comment]
@spaceoutlaws Could you try out one of the default presets? You might be using cfg which got removed. I didn't remove it from the plugin code yet.

**Comment by spaceoutlaws** [comment]
@SalokinGreen Still nothing... I tried a few of them, and was using a custom preset before that.

**Comment by SalokinGreen** [comment]
@spaceoutlaws Can you do me the favor and open the console with `ctrl+shift i` and send me a screenshot of what's saying when you generate? It works on my machine. 😓

**Comment by spaceoutlaws** [comment]
@SalokinGreen Of course! Here you go:
<img width="555" alt="image" src="https://github.com/user-attachments/assets/f6f95834-b5f2-457a-ac8c-2c77249f844b">

**Comment by SalokinGreen** [comment]
I could replicate the issue, actually. My api key stopped working, I generated a new one, and it works again. Could you please try that, too? @spaceoutlaws

**Comment by spaceoutlaws** [comment]
@SalokinGreen I'm still getting an error :( 
<img width="554" alt="image" src="https://github.com/user-attachments/assets/4601825a-7b6e-4691-a52c-432af7d66159">

**Comment by SalokinGreen** [comment]
@spaceoutlaws I installed a complete new version of the plugin in a new vault and it's still working for me. 🤔 Are you sure you updated it? 
![image](https://github.com/user-attachments/assets/44d4bb56-1e79-4644-a93c-abd960cc4eae)
Could you right click this and save the log, and send it to me? So that I can check the request.

**Comment by SalokinGreen** [comment]
@spaceoutlaws They apparently changed context validation. Your context might be too big and it gets blocked.
Could you try a new note?
![image](https://github.com/user-attachments/assets/283ace06-edc2-41c5-9507-18ccd0b1bd8a)

**Comment by SalokinGreen** [comment]
@spaceoutlaws I could finally replicate your issue! You're probably using too much output length!!!!
![image](https://github.com/user-attachments/assets/6f45ac6b-5201-46a9-acbf-25115f27ea39)

**Comment by spaceoutlaws** [comment]
@SalokinGreen Hmmm... I installed in a new vault and I'm still getting the issue, so it's definitely something on my end. Changing the output length doesn't seem to work either, and like I said, Clio's working fine, it's just Kayra that's giving me trouble. I'll keep troubleshooting!

**Comment by SalokinGreen** [comment]
@spaceoutlaws Off! Are you sure you put a number lower than the screenshot above? 150 for Opus and 100 for the other tiers. Try using something as low as 40? 
![image](https://github.com/user-attachments/assets/494be05e-9920-4ba6-a028-48e8118d471c)
Another issue might be you selecting the wrong sub and context size getting to big, but that can't be if you tried a completely empty context.
![image](https://github.com/user-attachments/assets/4ea07e15-a9c1-4315-8aab-26582d59693a)

Please do provide me with the request log as instructed above and/or send me your main.js file from the plugin folder. That's the 2 best options for me to see what's going on. 💚

**Comment by spaceoutlaws** [comment]
I tried 40 and am still getting the issue :') How do I attach my main.js file? Github is saying it's not a supported filetype.

I'm so sorry this is such a pain!

**Comment by SalokinGreen** [comment]
@spaceoutlaws No worries at all 🙏 I'm super happy to help out and I'm glad someone brings this up instead of users suffering in silence. 
You can just use a service like this https://www.file.io/ to upload your files. Getting your actual request would be more helpful, tho. Like instructed above.

**Comment by spaceoutlaws** [comment]
@SalokinGreen Oh, sorry!! I completely missed that part of the other message for some reason 😵‍💫 Okay, I'm sorry my writing is in here from last night, I couldn't figure out how to make it go away. If you read it, just pretend you didn't.

**Comment by SalokinGreen** [comment]
No worries, I promise I didn't read any of your writing! So new issue is that the log doesn't go that deep nested, so I don't see all your parameters! Please select one of the default presets to make sure you have the same gen settings as me, like Carefree, and then when the request is made, right click the parameters and "copy object". Please!
![image](https://github.com/user-attachments/assets/c4c94ced-3829-4de9-92f6-b317dfa3cfb5)

Should look like this:

{
    "max_length": 44,
    "top_p": 0.95,
    "top_a": 0.02,
    "temperature": 1.5,
    "repetition_penalty": 1.625,
    "typical_p": 0.95,
    "tail_free_sampling": 0.95,
    "repetition_penalty_range": 2016,
    "repetition_penalty_slope": 0,
    "repetition_penalty_frequency": 0,
    "repetition_penalty_presence": 0,
    "order": [
        8,
        0,
        5,
        3,
        2,
        4
    ],
    "logit_bias_exp": [
        {
            "sequence": [
                23
            ],
            "bias": -0.08,
            "ensure_sequence_finish": false,
            "generate_once": false
        },
        {
            "sequence": [
                21
            ],
            "bias": -0.08,
            "ensure_sequence_finish": false,
            "generate_once": false
        }
    ],
    "bad_words_ids": [
        [
            3
        ],
        [
            49356
        ],
        [
            1431
        ],
        [
            31715
        ],
        [
            34387
        ],
        [
            20765
        ],
        [
            30702
        ],
        [
            10691
        ],
        [
            49333
        ],
        [
            1266
        ],
        [
            19438
        ],
        [
            43145
        ],
        [
            26523
        ],
        [
            41471
        ],
        [
            2936
        ],
        [
            85,
            85
        ],
        [
            49332
        ],
        [
            7286
        ],
        [
            1115
        ]
    ],
    "repetition_penalty_whitelist": [
        49256,
        49264,
        49231,
        49230,
        49287,
        85,
        49255,
        49399,
        49262,
        336,
        333,
        432,
        363,
        468,
        492,
        745,
        401,
        426,
        623,
        794,
        1096,
        2919,
        2072,
        7379,
        1259,
        2110,
        620,
        526,
        487,
        16562,
        603,
        805,
        761,
        2681,
        942,
        8917,
        653,
        3513,
        506,
        5301,
        562,
        5010,
        614,
        10942,
        539,
        2976,
        462,
        5189,
        567,
        2032,
        123,
        124,
        125,
        126,
        127,
        128,
        129,
        130,
        131,
        132,
        588,
        803,
        1040,
        49209,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12
    ],
    "phrase_rep_pen": "very_aggressive",
    "mirostat_tau": 5,
    "mirostat_lr": 0.25,
    "generate_until_sentence": true,
    "prefix": "vanilla",
    "min_length": 1
}

**Comment by SalokinGreen** [comment]
@spaceoutlaws forgot the ping :)

**Comment by spaceoutlaws** [comment]
@SalokinGreen Okay, weird thing happened... I went to my new test vault to try to get a clean log and now it's working there with 40 tokens. Still not working on my main vault though, so I have a feeling it's something to do with my parameters. In any case, here's the new log, which uses a custom preset so it shouldn't match yours. (I also figured out how to get my writing to go away lol)

**Comment by SalokinGreen** [comment]
@spaceoutlaws Hey please try out one of the default settings. Your issue might be just that you're still using CFG which was removed. Like I said at the start 
![image](https://github.com/user-attachments/assets/4ddec44f-c5d6-444a-b08e-aeef4a5b8468)

**Comment by spaceoutlaws** [comment]
@SalokinGreen Ahhh, I didn't understand what you meant, I'm sorry 🤦🏻‍♀️ It's working now with the updated tokens AND a default setting. So sorry for all the trouble, I really appreciate you walking me through it.

**Comment by SalokinGreen** [comment]
@spaceoutlaws No worries, it happens! Going to remove cfg from the options asap to make sure nobody encounters this! :)
